### ISSUE TITLE
MouseGuard Localisation

### ISSUE THREAD

**Issue by Gumeg** [Roll20/roll20-character-sheets#5167]
Hello

Could be possible to upgrade MouseGuard Character Sheet to allow translations?

**Comment by JaegersNet** [comment]
I'll have a look at this ...

**Comment by JaegersNet** [comment]
done

**Comment by Gumeg** [comment]
Thank you a lot! Is it difficult for a githhub newbie to add a russian translation file? Anyway I'll try! 

I translate a Roll20 through a main site (Crowdin) and dont understand how quickly a translation become visible for an end user (palyer, DM).

**Comment by JaegersNet** [comment]
Git is cool and - in my opinion - awkward ... So, of you‘re not familiar with it, it might be easier to send the translation file to someone, who is. 

Updates to sheets and translations are published on a weekly base every Tuesday.

**Comment by Gumeg** [comment]
I made a translation file ru.json, but now it must be replace to folder "translations"..

**Comment by seriouslysean** [comment]
@JaegersNet thanks for doing those updates. I've been busy for a bit with life but I love seeing that the MouseGuard sheet is still getting updated. I had a request come in for a Korean translation also so I'll put a PR up for it as soon as I get the translations file. @Gumeg, if you want to send me the file I can submit a PR for you.

Just take a look at https://github.com/Roll20/roll20-character-sheets/blob/master/MouseGuard/translations/ru.json for an example on how to format the document.

**Comment by clevett** [comment]
@Gumeg Do you want to do translations? Email me at cassie@roll20.net and I'll get you an invite to Crowdin. Crowdin is an easy way to add translations and you wont need to know json. :)

**Comment by Gumeg** [comment]
> @Gumeg Do you want to do translations? Email me at [cassie@roll20.net](mailto:cassie@roll20.net) and I'll get you an invite to Crowdin. Crowdin is an easy way to add translations and you wont need to know json. :)

Thanks, but i'm allready in. =)
